### ISSUE TITLE
Comments when ; and /* are enclosed in brackets in if-clauses

### ISSUE THREAD

**Issue by ghost** [eneerge/mIRC-Scripting-Language-for-Sublime-Text#1]
Thanks for this syntax highlighter! 

I'm using it for a mIRC script called Peace and Protection. 

I've found that `/*` and `;` characters will break highlighting if those chars are enclosed by brackets in if-clauses.

What I mean, can be seen in the following examples:

> File: alias1.mrc - Line: 119
![image](https://user-images.githubusercontent.com/13683523/37662620-bcb82408-2c57-11e8-8ab1-c6c04b0f67ed.png)

> File: aliases.mrc - Line: 55
![image](https://user-images.githubusercontent.com/13683523/37662759-14ad00ca-2c58-11e8-8728-28532a3f6eba.png)

> File: first.mrc - Line: 1523
![image](https://user-images.githubusercontent.com/13683523/37662952-7cf9d8ce-2c58-11e8-9ad0-5df90cf3fca9.png)

I hope there's a fix for this :)

regards

**Comment by eneerge** [comment]
I have just updated the comment matching.  Let me know if this resolves the issue.

**Comment by ghost** [comment]
Seems to have fixed the issue! Cheers 👍
